apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ol8kym03a-python
  janus-idp.io/tekton: ol8kym03a-python
  backstage.io/kubernetes-id: ol8kym03a-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ol8kym03a-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
